name:                telegram-schedule-bot
version:             0.1.0.0
github:              "hrkcz001/telegram-schedule-bot"
license:             PADLA
author:              "hrkcz001"
copyright:           "2023 hrkcz001"

dependencies:
- base >= 4.7 && < 5
- wreq
- bytestring
- aeson
- yaml
- containers
- lens
- lens-aeson
- vector
- text
- scientific
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  telegram-schedule-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telegram-schedule-bot